# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 007ba17c941051ecffa81a6f23d334d9a2b0b5fed0d8f1d8b4de788357f86ce42e9845f0071c1645760cac9b23e02e32ac213edb2d243d92289aa3d20106af75

test:
  secret_key_base: 2ebc04368bf0b8ac60ee5b676567414534e940d22817d9cb9c49ed53130c3cadeb0e2efea3204465a93387b4561771e5e3f4f9bd9aea316a134dbb298a8d04be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["QIANYAN_FORM_SECRET_KEY_BASE"] %>
